### ISSUE TITLE
Translation - Way forward

### ISSUE THREAD

**Issue by gcharest** [StatCan/katacoda-courses#1]
Hi @sylus ! Just wanted to reach out to see how we can help having the content available in French?

Would you like to add me as contributor on this repo for a while?

**Comment by gcharest** [comment]
Or @zachomedia!

**Comment by sylus** [comment]
Added you :D Happy for any and all help!

**Comment by gcharest** [comment]
Hi @sylus,

I probably don't still have the rights to push. Working on a PR in the meantime.

Thanks!

**Comment by sylus** [comment]
Hey @gcharest you have perms now ^_^
